=== BenRutlandWeb/recipeasy/src/schemas/recipe.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Recipe",
  "type": "object",
  "required": [
    "title",
    "description",
    "serves",
    "prepTime",
    "cookTime",
    "image",
    "keywords",
    "ingredients",
    "methods"
  ],
  "properties": {
    "$schema": {
      "type": "string"
    },
    "title": {
      "type": "string",
      "description": "The title of the recipe"
    },
    "description": {
      "type": "string",
      "description": "A short description of the recipe"
    },
    "image": {
      "type": "string",
      "description": "An image path"
    },
    "serves": {
      "type": "integer",
      "description": "The number of servings"
    },
    "prepTime": {
      "type": "integer",
      "description": "Preparation time in minutes"
    },
    "cookTime": {
      "type": "integer",
      "description": "Cooking time in minutes"
    },
    "keywords": {
      "type": "array",
      "description": "List of keywords for categorizing the recipe. E.g. Dinner, Breakfast, Meat, Vegan. Avoid ingredients.",
      "items": {
        "type": "string"
      }
    },
    "ingredients": {
      "type": "array",
      "description": "A list of ingredients",
      "items": {
        "$ref": "ingredient.json"
      }
    },
    "methods": {
      "type": "array",
      "description": "Step-by-step instructions",
      "items": {
        "type": "string"
      }
    },
    "diet": {
      "$ref": "diet.json"
    },
    "spiceLevel": {
      "type": "integer",
      "minimum": 0,
      "maximum": 3,
      "default": 0
    }
  },
  "additionalProperties": false
}

=== BenRutlandWeb/recipeasy/src/data/recipes/roast-chorizo-chicken.json
{
  "$schema": "../../schemas/recipe.json",
  "title": "Roast chorizo chicken",
  "ingredients": [
    { "name": "new potatoes", "quantity": 500, "unit": "g" },
    { "name": "olive oil", "quantity": 2, "unit": "tbsp" },
    {
      "name": "chicken thighs",
      "quantity": 8,
      "description": "Skinless and boneless"
    },
    { "name": "soked paprika", "quantity": 1, "unit": "tsp" },
    { "name": "thyme", "quantity": 1, "unit": "tsp" },
    { "name": "chorizo", "quantity": 115, "unit": "g" },
    { "name": "cherry tomatoes", "quantity": 150 },
    { "name": "garlic cloves", "quantity": 4 },
    { "name": "parsley", "quantity": 10, "unit": "g" }
  ],
  "methods": [
    "Preheat the oven to 220C/200C Fan/Gas 7. Halve or quarter the potatoes, depending on their size (to produce evenly sized chunks). Place in a large non-stick roasting tin. Toss with two tbsp of the oil and season to taste with salt and pepper, then put into the oven for 15 minutes.",
    "Cut the chicken thighs in half, add the smoked paprika and cinnamon, if using. Scatter with half the thyme leaves, season with salt and pepper, stir through and set aside.",
    "Make a nick in the skin of the chorizo then, peel away the papery skin. Cut the sausage into chunks or rounds.",
    "When the potatoes have had 15 minutes roasting, give them a stir, then nestle the chicken and tomatoes into the pan. Scatter with the chorizo, garlic and the remaining thyme leaves, then season with salt and pepper.",
    "Drizzle the remaining oil all over, and return to the oven to roast for 20 minutes more, stirring half-way, until the chicken is cooked through and the potatoes and tomatoes are turning golden brown and crisp at the edges.",
    "Scatter the dish with a handful roughly chopped parsley, and serve."
  ],
  "keywords": ["Dinner", "Meat"],
  "image": "roast-chorizo-chicken.webp",
  "description": "Tasty chicken and chorizo roasted in the same tin, infusing great paprika and herb flavours, and saving on washing up.",
  "serves": 4,
  "prepTime": 15,
  "cookTime": 45
}

=== BenRutlandWeb/recipeasy/src/data/recipes/one-pot-hunters-chicken-rice.json
{
  "$schema": "../../schemas/recipe.json",
  "title": "One-pot hunters chicken and rice",
  "ingredients": [
    {
      "name": "chicken breast",
      "quantity": 500,
      "unit": "g",
      "description": "Diced"
    },
    { "name": "bacon", "quantity": 150, "unit": "g", "description": "Diced" },
    { "name": "onion", "quantity": 1, "description": "Diced" },
    { "name": "garlic cloves", "quantity": 2, "description": "Finely chopped" },
    { "name": "BBQ seasoning", "quantity": 1, "unit": "tbsp" },
    { "name": "smoked paprika", "quantity": 1, "unit": "tbsp" },
    { "name": "tomato puree", "quantity": 1, "unit": "tbsp" },
    { "name": "BBQ sauce", "quantity": 1, "unit": "tbsp" },
    { "name": "basmati rice", "quantity": 250, "unit": "g" },
    { "name": "chicken stock", "quantity": 600, "unit": "ml" },
    {
      "name": "cheese",
      "quantity": 120,
      "unit": "g",
      "description": "Cheddar or Red Leicester"
    },
    { "name": "Parsley", "description": "To serve" }
  ],
  "methods": [
    "Fry the chicken, bacon and the seasoning in a large pan.",
    "Add the onion and cook until soft.",
    "Add the garlic, tomato puree and BBQ sauce and cook for a few minutes.",
    "Add the rice and chicken stock, place a lid on the pan and cook on a low heat for 20 mins.",
    "Sprinkle over the cheese and place under the grill until golden and bubbling.",
    "Drizzle over more BBQ sauce and parsley and serve."
  ],
  "keywords": ["Dinner", "Meat"],
  "image": "one-pot-hunters-chicken-rice.jpg",
  "description": "",
  "serves": 4,
  "prepTime": 10,
  "cookTime": 45
}

=== BenRutlandWeb/recipeasy/src/data/recipes/healthy-beef-chow-mein.json
{
  "$schema": "../../schemas/recipe.json",
  "title": "Healthy beef chow mein",
  "ingredients": [
    { "name": "egg noodle nests", "quantity": 2 },
    { "name": "sesame oil", "quantity": 2, "unit": "tsp" },
    {
      "name": "fillet steak",
      "quantity": 200,
      "unit": "g",
      "description": "Cut into strips"
    },
    { "name": "red onion", "quantity": 1, "description": "Finely chopped" },
    {
      "name": "ginger",
      "quantity": 15,
      "unit": "g",
      "description": "Peeled and finely chopped"
    },
    {
      "name": "chestnut mushrooms",
      "quantity": 160,
      "unit": "g",
      "description": "Thickly sliced"
    },
    { "name": "garlic cloves", "quantity": 2, "description": "Finely chopped" },
    { "name": "beansprouts", "quantity": 160, "unit": "g" },
    { "name": "tamari", "quantity": 1.5, "unit": "tsp" },
    { "name": "brown rice vinegar", "quantity": 1, "unit": "tbsp" },
    {
      "name": "spring onions",
      "quantity": 4,
      "description": "Cut into diagonal lengths"
    }
  ],
  "methods": [
    "Cook the noodles following pack instructions. Meanwhile, heat half the oil in a wok and stir-fry the beef over a high heat for 30 seconds until browned. Tip onto a plate, set aside, then add the remaining oil to the wok. Stir-fry the onion and ginger until softened. Add a drop of water to prevent burning, if needed and cook covered for 2-3 mins.",
    "Stir in the mushrooms and garlic, and fry until they start to soften (around 3 mins), then add the beansprouts and cook for a minute or two more until piping hot.",
    "Mix the tamari and vinegar together in a small bowl with 2 tbsp water. Add the drained noodles to the wok, toss well, then add the tamari mixture, spring onions and the beef. Stir-fry for a few minutes until heated through. Season with plenty of black pepper and serve."
  ],
  "keywords": ["Dinner", "Meat", "Chinese", "Asian"],
  "image": "/recipeasy/healthy-beef-chow-mein.webp",
  "description": "Swap your weekly takeaway for this healthy beef chow mein - it's quick to cook and low in fat and calories.",
  "serves": 2,
  "prepTime": 10,
  "cookTime": 10
}

=== BenRutlandWeb/recipeasy/src/data/recipes/cucumber-in-vinegar-and-chili-sauce.json
{
    "$schema": "../../schemas/recipe.json",
    "title": "Cucumber in vinegar and chili sauce",
    "ingredients": [
        { "name": "cucumber", "quantity": 150, "unit": "g", "description": "Roughly chopped" },
        { "name": "garlic cloves", "quantity": 3, "description": "Crushed" },
        {
            "name": "deep-fried peanuts",
            "quantity": 10,
            "description": "Finely chopped"
        },
        { "name": "dark rice vinegar", "quantity": 3, "unit": "tbsp" },
        { "name": "light soy sauce", "quantity": 2, "unit": "tbsp" },
        { "name": "salt", "quantity": 0.5, "unit": "tsp" },
        { "name": "sugar", "quantity": 1, "unit": "tbsp" },
        { "name": "chili oil", "quantity": 1, "unit": "tbsp" },
        { "name": "Sesame oil", "description": "A few drops" }
    ],
    "methods": [
        "In a bowl mix together the dark rice vinegar, light soy sauce, salt, sugar and chili oil.",
        "Add in the garlic and a few drops of sesame oil then add the cucumber. Top with the deep-fried peanuts."
    ],
    "keywords": ["Dinner", "Vegetarian", "Chinese"],
    "image": "/recipeasy/cucumber-in-vinegar-and-chili-sauce.webp",
    "description": "",
    "serves": 2,
    "prepTime": 5,
    "cookTime": 5,
    "spiceLevel": 1
}

=== BenRutlandWeb/recipeasy/src/data/recipes/crispy-salmon-tacos.json
{
    "$schema": "../../schemas/recipe.json",
    "title": "Crispy salmon tacos",
    "ingredients": [
        { "name": "cherry tomatoes", "quantity": 160, "unit": "g" },
        { "name": "mango", "quantity": 1, "description": "Small" },
        { "name": "Avocado", "quantity": 0.5 },
        { "name": "spring onions", "quantity": 2 },
        {
            "name": "salmon fillets",
            "quantity": 2,
            "description": "skin on, scaled, pin-boned"
        },
        { "name": "cajun seasoning", "quantity": 2, "unit": "tsp" },
        { "name": "tortillas", "quantity": 4, "description": "Small" },
        { "name": "limes", "quantity": 2 }
    ],
    "methods": [
        "Quarter the cherry tomatoes. Destone, peel and roughly chop the mango. Scoop out the avocado and finely slice. Trim and finely slice the spring onions.",
        "Carefully cut the skin off the salmon and place it in a non-stick frying pan on a medium-high heat to crisp up on both sides.",
        "Pat the Cajun seasoning all over the salmon fillets, then fry for 5 minutes, turning to get them golden on each of their sides. Once the skin is crispy, move it to sit on top of the salmon.",
        "Meanwhile, use tongs to toast the tortillas directly over the flame of your gas hob for 15 seconds, or use a hot pan.",
        "Sprinkle the mango, avocado and spring onions over the tortillas, then flake over the salmon and crack over the skin.",
        "Toss the tomatoes and the juice of 1 lime in the residual heat of the pan for 30 seconds, then spoon over the tortillas.",
        "Serve with lime wedges, for squeezing over."
    ],
    "keywords": ["Dinner", "Fish"],
    "image": "/recipeasy/crispy-salmon-tacos.webp",
    "description": "Smoky chorizo salmon with sweet cherry tomatoes and basil.",
    "serves": 2,
    "prepTime": 10,
    "cookTime": 20
}

=== BenRutlandWeb/recipeasy/src/data/recipes/chorizo-and-mozzarella-gnocchi-bake.json
{
  "$schema": "../../schemas/recipe.json",
  "title": "Chorizo and mozzarella gnocchi bake",
  "ingredients": [
    { "name": "olive oil", "quantity": 1, "unit": "tbsp" },
    { "name": "onion", "quantity": 1, "description": "Finely chopped" },
    { "name": "garlic cloves", "quantity": 2, "description": "Crushed" },
    { "name": "chorizo", "quantity": 120, "unit": "g", "description": "Diced" },
    { "name": "chopped tomatoes", "quantity": 800, "unit": "g" },
    { "name": "caster sugar", "quantity": 1, "unit": "tsp" },
    { "name": "gnocci", "quantity": 600, "unit": "g" },
    {
      "name": "mozzarella cheese",
      "quantity": 125,
      "unit": "g",
      "description": "Cut into chunks"
    },
    { "name": "Basil", "quantity": 15, "unit": "g", "description": "Torn" }
  ],
  "methods": [
    "Heat the oil in a medium pan over a medium heat. Fry the onion and garlic for 8-10 mins until soft.",
    "Add the chorizo and fry for 5 mins more.",
    "Tip in the tomatoes and sugar, and season. Bring to a simmer, then add the gnocchi and cook for 8 mins, stirring often, until soft.",
    "Heat the grill to high. Stir 3/4 of the mozzarella and most of the basil through the gnocchi.",
    "Divide the mixture between six ovenproof ramekins, or put in one baking dish. Top with the remaining mozzarella, then grill for 3 mins, or until the cheese is melted and golden.",
    "Season, scatter over the remaining basil and serve with green salad."
  ],
  "keywords": ["Dinner", "Meat"],
  "image": "/recipeasy/chorizo-and-mozzarella-gnocchi-bake.webp",
  "description": "Upgrade cheesy tomato pasta with gnocchi, chorizo and mozzarella for a comforting bake that makes an excellent midweek meal.",
  "serves": 4,
  "prepTime": 10,
  "cookTime": 25
}

=== BenRutlandWeb/recipeasy/src/data/recipes/spanish-chicken-traybake.json
{
  "$schema": "../../schemas/recipe.json",
  "title": "Spanish chicken traybake",
  "ingredients": [
    { "name": "olive oil", "quantity": 2, "unit": "tbsp" },
    {
      "name": "red onions",
      "quantity": 2,
      "description": "Each cut into 8 wedges"
    },
    {
      "name": "baby new potatoes",
      "quantity": 500,
      "unit": "g",
      "description": "Halved if large"
    },
    { "name": "chicken thigh fillets", "quantity": 8 },
    { "name": "smoked paprika", "quantity": 0.5, "unit": "tsp" },
    {
      "name": "red pepper",
      "quantity": 1,
      "description": "Deseeded and sliced"
    },
    {
      "name": "yellow pepper",
      "quantity": 1,
      "description": "Deseeded and sliced"
    },
    { "name": "tomatoes", "quantity": 4, "description": "Quartered" },
    {
      "name": "chorizo",
      "quantity": 125,
      "unit": "g",
      "description": "Sliced into rounds"
    },
    { "name": "black olives", "quantity": 50, "unit": "g" },
    { "name": "garlic cloves", "quantity": 2, "description": "Crushed" },
    { "name": "oregano", "quantity": 1, "unit": "tsp" },
    { "name": "Manzilla sherry", "quantity": 50, "unit": "ml" }
  ],
  "methods": [
    "Preheat oven to 200°C (180°C fan) mark 6. Toss the oil, onions, potatoes and some seasoning in a large roasting tin. Roast for 30min.",
    "Slash the top of each chicken thigh a couple of times and sprinkle over the paprika and plenty of freshly ground black pepper.",
    "Mix the peppers, tomatoes, chorizo, olives and garlic into the roasting tin and sprinkle over the oregano. Sit the chicken on top and add the sherry, if using.",
    "Continue roasting for 40-45min, basting the chicken midway through with any juices in the pan. Serve with a crisp green salad and some bread to mop up the juices, if you like."
  ],
  "keywords": ["Dinner", "Spanish", "Meat"],
  "image": "spanish-chicken-traybake.jpg",
  "description": "A chicken tray bake full of sunshine flavours. If you'd prefer not to use sherry, substitute with chicken stock instead. Serve it with a crisp green salad or a decent loaf of crusty bread.",
  "serves": 4,
  "prepTime": 20,
  "cookTime": 75
}

=== BenRutlandWeb/recipeasy/src/data/recipes/millies-cookies.json
{
  "$schema": "../../schemas/recipe.json",
  "title": "Millie's cookies",
  "description": "These delicious cookies are easy to cook and taste as good as the real Millies cookies, with a crisp outer layer and a gooey centre these treats are best eaten warm but last well...if they last that long!!!",
  "image": "/recipeasy/millies-cookies.jpg",
  "serves": 12,
  "prepTime": 5,
  "cookTime": 10,
  "keywords": ["Sweet treats", "Baking", "Cookies"],
  "ingredients": [
    {
      "name": "butter",
      "quantity": 125,
      "unit": "g",
      "description": "softened"
    },
    {
      "name": "light brown soft sugar",
      "quantity": 100,
      "unit": "g"
    },
    {
      "name": "caster sugar",
      "quantity": 125,
      "unit": "g"
    },
    {
      "name": "egg",
      "quantity": 1,
      "description": "lightly beaten"
    },
    {
      "name": "vanilla extract",
      "quantity": 1,
      "unit": "tsp"
    },
    {
      "name": "self-raising flour",
      "quantity": 225,
      "unit": "g"
    },
    {
      "name": "salt",
      "quantity": 0.5,
      "unit": "tsp"
    },
    {
      "name": "chocolate chips",
      "quantity": 200,
      "unit": "g"
    }
  ],
  "methods": [
    "Preheat the oven to 180Â°C, gas mark 4.",
    "Cream butter and sugars, once creamed, combine in the egg and vanilla.",
    "Sift in the flour and salt, then the chocolate chips.",
    "Roll into walnut size balls, for a more homemade look, or roll into a long, thick sausage shape and slice to make neater looking cookies.",
    "Place on ungreased baking paper. If you want to have the real Millies experience then bake for just 7 minutes, till the cookies are just setting - the cookies will be really doughy and delicious. Otherwise cook for 10 minutes until just golden round the edges.",
    "Take out of the oven and leave to harden for a minute before transferring to a wire cooling rack. These are great warm, and they also store well, if they don't all get eaten straight away!"
  ]
}
